version: "3.9"

services:
  nginx:
    image: nginx:latest
    container_name: nextjs-nginx
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./public:/usr/share/nginx/html:ro
